INSERT INTO prime.item (
    id,
    part_number,
    brand_name,
    mfr_part_number,
    my_part_number,
    upc,
    country_of_origin,
    country_of_sale,
    gtin,
    short_description,
    long_description,
    feature_bullets,
    invoice_description,
    print_description,
    pack_description,
    qty_available,
    min_order_qty,
    package_length,
    package_length_uom,
    package_height,
    package_height_uom,
    package_weight,
    package_weight_uom,
    package_width,
    package_width_uom,
    volume,
    volume_uom,
    standard_approval,
    status,
    warranty,
    enriched_indicator,
    manufacturer_status,
    created_at,
    updated_at
)
OVERRIDING SYSTEM VALUE
VALUES
(
    10001,
    'PartNo001',
    'viru@',
    'p1manf01',
    'mypart001',
    '123',
    'IN',
    'US',
    '1312312343',
    'this is short description',
    'this is long description',
    'new feature and old feature',
    'this is invoice description',
    'newly print description',
    'packing description',
    10000,
    100,
    10.00,
    '10',
    23.00,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'INACTIVE',
    NULL,
    'ENRICHED',
    'ACTIVE',
    NOW(),
    NOW()
),
(
    10002,
    'PartNo002',
    'audi@',
    'p1manf02',
    'mypart002',
    '1234',
    'IN',
    'US',
    '131231234343',
    NULL,
    'this is long description',
    'new feature and old feature',
    'this is invoice description',
    'newly print description',
    'packaging description',
    10000,
    100,
    100.00,
    '10',
    25.00,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'ACTIVE',
    NULL,
    'ENRICHED',
    'INACTIVE',
    NOW(),
    NOW()
);
